config/routes.rb
Rails.application.routes.draw do
  root 'weather#index'

  get 'weather/index'
  get 'weather/data', defaults: { format: 'json' }

  get 'weather/heatmap'
  get 'weather/heatmap_data', defaults: { format: 'json' }

  get 'map/index'
  get 'map/map_data', defaults: { format: 'json' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/weather_reading.rb
class WeatherReading < ApplicationRecord
  has_one :weather_station, foreign_key: 'station_id', primary_key: 'station'

  scope :temps, -> { where(reading_type: ["TMAX", "TMIN"]) }
  scope :with_weather_station, -> { joins(:weather_station) }
  scope :with_fields, -> { select("weather_readings.id, reading_date, reading_type, reading_value, source_flag, latitude, longitude, elevation, name") }
  scope :for_station, ->(station) { with_weather_station.with_fields.where("weather_stations.name = ?", station) }
  scope :sorted, -> { order("reading_type, reading_date") }
  scope :for_year, ->(year) { where(reading_date: Date.new(year, 1, 1)..Date.new(year + 1, 1, 1)) }

  def self.heatmap(station)
    sql = <<-SQL.strip_heredoc
      WITH days AS (
        SELECT dt
        FROM generate_series(
          '18360101'::timestamp, '18361231'::timestamp, '1 day'
        ) AS dt
      ), temperature_readings AS (
        SELECT id, reading_date, reading_value
        FROM weather_readings
        WHERE reading_type = 'TMAX'
          AND station = '#{station}'
        ORDER BY 2
      )
      SELECT tr.*
      FROM temperature_readings tr
      RIGHT JOIN days ON reading_date >= days.dt AND reading_date <= days.dt;
    SQL
    connection.execute(sql)
  end
end

app/models/weather_station.rb
class WeatherStation < ApplicationRecord
  belongs_to :weather_reading
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  layout "map"

  def index; end

  def map_data
    sql = <<-SQL.strip_heredoc
      SELECT *
      FROM weather_stations
      WHERE station_id IN (
        SELECT DISTINCT station
        FROM weather_readings
        WHERE reading_date = '1940-01-01'
          AND reading_type IN ('TMAX', 'TMIN')
      )
    SQL
    @stations = ActiveRecord::Base.connection.execute(sql)
  end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def index
  end

  def data
    year     = params[:year] || 1836
    readings = WeatherReading.temps.for_station('MILAN').for_year(year).sorted
    render json: { readings: readings }
  end

  def heatmap
  end

  def heatmap_data
    data = WeatherReading.heatmap('ITE00100554')
    render json: data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="navbar">
        <div class="nav1">
          <h1>Weather</h1>
        </div>
        <div class="nav2">
          <ul>
            <li><a href="#"><%= link_to "Weather Stations", map_index_url %></a></li>
            <li><a href="#"><%= link_to "Heat Map", weather_heatmap_url %></a></li>
            <li><a href="#"><%= link_to "Linechart", weather_index_url %></a></li>
          </ul>
        </div>
      </div>
    </header>
    <div class="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NOAA Weather Data</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://api.tiles.mapbox.com/mapbox.js/v2.2.4/mapbox.js" %>
  <%= stylesheet_link_tag "https://api.tiles.mapbox.com/mapbox.js/v2.2.4/mapbox.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body data-mapbox-token="<%= ENV['MAPBOX_TOKEN'] %>">

 <%= yield %>

</body>
</html>

app/views/map/index.html.erb
<script>
$(document).on('ready page:load', function(event) {
  // apply non-idempotent transformations to the body
  makeMap();
});
</script>
 <!-- A map will magically appear here -->
<div id="map"></div>

app/views/weather/heatmap.html.erb
<script>
$(document).on('ready page:load', function(event) {
  makeHeatMap();
});
</script>

app/views/weather/index.html.erb
<script>
$(document).on('ready page:load', function(event) {
  makeLineChart();
});
</script>